arduino-cli lib install "Adafruit GFX Library"
arduino-cli lib install "Adafruit LED Backpack Library"
arduino-cli lib install "DS3231"
arduino-cli lib install "Adafruit AW9523"
arduino-cli lib install "CD74HC4067"
